name: Main
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.19.x", "1.20.x"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3.2.0
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: Dependencies
        run: go mod tidy
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
      - name: test
        run: |
          make test
          cp .tests/coverage.html .tests/coverage-${{ matrix.go-version }}.html
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage-${{ matrix.go-version }}
          path: .tests/coverage-${{ matrix.go-version }}.html